v1 = input('type something: ')
type(v1)
print('The thing that you typed is numeric: ?',v1.isnumeric())
print('The thing that you typed is letter : ?' ,v1.isalpha())
print('The thing that you typed is alphanumeric: ?' ,v1.isalnum())
print('The thing that you typed is normal letters  : ?',v1.islower())
print('The thing that you typed is decimal: ?',v1.isdecimal())
print('The thing that you typed is CapsLk: ?',v1.isupper())
print('The thing that you typed there is the first letter Upper? {}'.format(v1.istitle()))
